// <auto-generated />
using System;
using DataAccessLayer.Abstract;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EntityLayer.Concrete.TBL_BOLUM", b =>
                {
                    b.Property<int>("BOLUM_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BOLUM_ID"), 1L, 1);

                    b.Property<string>("ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<string>("OZEL_KOD")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BOLUM_ID");

                    b.ToTable("TBL_BOLUM");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_DERS", b =>
                {
                    b.Property<int>("DERS_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DERS_ID"), 1L, 1);

                    b.Property<string>("ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<string>("OZEL_KOD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SCHOOL_ID")
                        .HasColumnType("int");

                    b.HasKey("DERS_ID");

                    b.ToTable("TBL_DERS");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_DERS_PROGRAMI", b =>
                {
                    b.Property<int>("DERS_PROGRAM_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DERS_PROGRAM_ID"), 1L, 1);

                    b.Property<int?>("DERS_ID")
                        .HasColumnType("int");

                    b.Property<int?>("DONEM_ID")
                        .HasColumnType("int");

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<string>("GUN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OGRETMENIDARI_PERSONEL_ID")
                        .HasColumnType("int");

                    b.Property<string>("OZEL_KOD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SCHOOL_ID")
                        .HasColumnType("int");

                    b.Property<int?>("SINIF_ID")
                        .HasColumnType("int");

                    b.Property<int?>("SUBE_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TARIH")
                        .HasColumnType("datetime2");

                    b.Property<int>("USER_ID")
                        .HasColumnType("int");

                    b.HasKey("DERS_PROGRAM_ID");

                    b.HasIndex("DERS_ID");

                    b.HasIndex("DONEM_ID");

                    b.HasIndex("OGRETMENIDARI_PERSONEL_ID");

                    b.HasIndex("SCHOOL_ID");

                    b.HasIndex("SINIF_ID");

                    b.HasIndex("SUBE_ID");

                    b.ToTable("TBL_DERS_PROGRAMI");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_DERSLER", b =>
                {
                    b.Property<int>("DERSLER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DERSLER_ID"), 1L, 1);

                    b.Property<string>("ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<string>("OZEL_KOD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SCHOOL_ID")
                        .HasColumnType("int");

                    b.HasKey("DERSLER_ID");

                    b.HasIndex("SCHOOL_ID");

                    b.ToTable("TBL_DERSLER");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_DONEM", b =>
                {
                    b.Property<int>("DONEM_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DONEM_ID"), 1L, 1);

                    b.Property<string>("ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<string>("OZEL_KOD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SCHOOL_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TARIH")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TBL_IDARI_PERSONELIDARI_PERSONEL_ID")
                        .HasColumnType("int");

                    b.Property<int>("USER_ID")
                        .HasColumnType("int");

                    b.HasKey("DONEM_ID");

                    b.HasIndex("TBL_IDARI_PERSONELIDARI_PERSONEL_ID");

                    b.ToTable("TBL_DONEM");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_IDARI_PERSONEL", b =>
                {
                    b.Property<int>("IDARI_PERSONEL_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDARI_PERSONEL_ID"), 1L, 1);

                    b.Property<string>("ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<string>("MAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OZEL_KOD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SCHOOL_ID")
                        .HasColumnType("int");

                    b.Property<string>("SIFRE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SOYADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TELEFON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNVAN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDARI_PERSONEL_ID");

                    b.HasIndex("SCHOOL_ID");

                    b.ToTable("TBL_IDARI_PERSONEL");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_KURUM", b =>
                {
                    b.Property<int>("KURUM_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KURUM_ID"), 1L, 1);

                    b.Property<int>("AKTIF_DONEM")
                        .HasColumnType("int");

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<string>("KURUM_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KURUM_LISANS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KURUM_LOGO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OZEL_KOD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SCHOOL_ID")
                        .HasColumnType("int");

                    b.HasKey("KURUM_ID");

                    b.HasIndex("SCHOOL_ID");

                    b.ToTable("TBL_KURUM");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_LOG", b =>
                {
                    b.Property<int>("TBL_LOG_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TBL_LOG_ID"), 1L, 1);

                    b.Property<DateTime>("CIKIS")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GIRIS")
                        .HasColumnType("datetime2");

                    b.Property<string>("OZEL_KOD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SCHOOL_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TARIH")
                        .HasColumnType("datetime2");

                    b.Property<int>("USER_ID")
                        .HasColumnType("int");

                    b.HasKey("TBL_LOG_ID");

                    b.HasIndex("SCHOOL_ID");

                    b.ToTable("TBL_LOG");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_MESAJ_HAREKETLERI", b =>
                {
                    b.Property<int>("MESAJ_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MESAJ_ID"), 1L, 1);

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<int>("KULLANICI_ID")
                        .HasColumnType("int");

                    b.Property<string>("KULLANICI_TURU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MESAJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OZEL_KOD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SAAT")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SCHOOL_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TARIH")
                        .HasColumnType("datetime2");

                    b.Property<int>("USER_ID")
                        .HasColumnType("int");

                    b.HasKey("MESAJ_ID");

                    b.HasIndex("SCHOOL_ID");

                    b.ToTable("TBL_MESAJ_HAREKETLERI");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_MESAJ_PATH", b =>
                {
                    b.Property<int>("MESAJ_PATH_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MESAJ_PATH_ID"), 1L, 1);

                    b.Property<string>("API")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("API_KEY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHARSET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<string>("FIRMA_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OZEL_KOD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SCHOOL_ID")
                        .HasColumnType("int");

                    b.Property<string>("SENDER")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MESAJ_PATH_ID");

                    b.HasIndex("SCHOOL_ID");

                    b.ToTable("TBL_MESAJ_PATH");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_OGRENCI", b =>
                {
                    b.Property<int>("OGRENCI_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OGRENCI_ID"), 1L, 1);

                    b.Property<string>("ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BOLUM_ID")
                        .HasColumnType("int");

                    b.Property<int?>("DONEM_ID")
                        .HasColumnType("int");

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<string>("MAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OKUL_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OZEL_KOD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SCHOOL_ID")
                        .HasColumnType("int");

                    b.Property<string>("SINIF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SOYADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUBE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TARIH")
                        .HasColumnType("datetime2");

                    b.Property<string>("TELEFON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("USER_ID")
                        .HasColumnType("int");

                    b.Property<string>("VATADANDAS_NO")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OGRENCI_ID");

                    b.HasIndex("BOLUM_ID");

                    b.HasIndex("DONEM_ID");

                    b.HasIndex("SCHOOL_ID");

                    b.ToTable("TBL_OGRENCI");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_SCHOOL_DURUMLARI", b =>
                {
                    b.Property<int>("SCHOOL_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SCHOOL_ID"), 1L, 1);

                    b.Property<DateTime>("BASLAMA_TARIHI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BITIS_TARIHI")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<DateTime>("GUNCELLENEME_TARIHI")
                        .HasColumnType("datetime2");

                    b.Property<string>("KURUM_KODU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LISANS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OKUL_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OKUL_FAX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OKUL_MAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OKUL_TELOFON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SORUMLU_YETKILI1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SORUMLU_YETKILI2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SORUMLU_YETKILI_NUMARA1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SORUMLU_YETKILI_NUMARA2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SCHOOL_ID");

                    b.ToTable("TBL_SCHOOL_DURUMLARI");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_SINIF", b =>
                {
                    b.Property<int>("SINIF_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SINIF_ID"), 1L, 1);

                    b.Property<string>("ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<string>("OZEL_KOD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SCHOOL_ID")
                        .HasColumnType("int");

                    b.HasKey("SINIF_ID");

                    b.HasIndex("SCHOOL_ID");

                    b.ToTable("TBL_SINIF");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_SUBE", b =>
                {
                    b.Property<int>("SUBE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SUBE_ID"), 1L, 1);

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<string>("OZEL_KOD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SCHOOL_ID")
                        .HasColumnType("int");

                    b.HasKey("SUBE_ID");

                    b.HasIndex("SCHOOL_ID");

                    b.ToTable("TBL_SUBE");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_TRY_CATCH", b =>
                {
                    b.Property<int>("TRY_CATCH_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TRY_CATCH_ID"), 1L, 1);

                    b.Property<DateTime>("DATE")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<string>("ERROR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISLEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OZEL_KOD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SCHOOL_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TIME")
                        .HasColumnType("datetime2");

                    b.HasKey("TRY_CATCH_ID");

                    b.HasIndex("SCHOOL_ID");

                    b.ToTable("TBL_TRY_CATCH");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_VELI", b =>
                {
                    b.Property<int>("VELI_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VELI_ID"), 1L, 1);

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<string>("MAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OGRENCI_ID")
                        .HasColumnType("int");

                    b.Property<string>("OZEL_KOD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SCHOOL_ID")
                        .HasColumnType("int");

                    b.Property<string>("SOYADI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TARIH")
                        .HasColumnType("datetime2");

                    b.Property<string>("TELEFON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("USER_ID")
                        .HasColumnType("int");

                    b.HasKey("VELI_ID");

                    b.HasIndex("OGRENCI_ID");

                    b.HasIndex("SCHOOL_ID");

                    b.ToTable("TBL_VELI");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_YOKLAMA_HAREKETLERI", b =>
                {
                    b.Property<int>("YOKLAMA_HAREKETLERI_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YOKLAMA_HAREKETLERI_ID"), 1L, 1);

                    b.Property<int?>("DONEM_ID")
                        .HasColumnType("int");

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<bool>("EOKUL_DURUM")
                        .HasColumnType("bit");

                    b.Property<bool>("MESAJ_DURUM")
                        .HasColumnType("bit");

                    b.Property<int?>("OGRENCI_ID")
                        .HasColumnType("int");

                    b.Property<string>("OZEL_KOD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PROGRAMDERS_PROGRAM_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SAAT")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SCHOOL_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TARIH")
                        .HasColumnType("datetime2");

                    b.HasKey("YOKLAMA_HAREKETLERI_ID");

                    b.HasIndex("DONEM_ID");

                    b.HasIndex("OGRENCI_ID");

                    b.HasIndex("PROGRAMDERS_PROGRAM_ID");

                    b.HasIndex("SCHOOL_ID");

                    b.ToTable("TBL_YOKLAMA_HAREKETLERI");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_DERS_PROGRAMI", b =>
                {
                    b.HasOne("EntityLayer.Concrete.TBL_DERS", "DERS")
                        .WithMany("TBL_DERS_PROGRAMIS")
                        .HasForeignKey("DERS_ID");

                    b.HasOne("EntityLayer.Concrete.TBL_DONEM", "DONEM")
                        .WithMany("TBL_DERS_PROGRAMIS")
                        .HasForeignKey("DONEM_ID");

                    b.HasOne("EntityLayer.Concrete.TBL_IDARI_PERSONEL", "OGRETMEN")
                        .WithMany()
                        .HasForeignKey("OGRETMENIDARI_PERSONEL_ID");

                    b.HasOne("EntityLayer.Concrete.TBL_SCHOOL_DURUMLARI", "SCHOOL")
                        .WithMany()
                        .HasForeignKey("SCHOOL_ID");

                    b.HasOne("EntityLayer.Concrete.TBL_SINIF", "SINIF")
                        .WithMany("TBL_DERS_PROGRAMIS")
                        .HasForeignKey("SINIF_ID");

                    b.HasOne("EntityLayer.Concrete.TBL_SUBE", "SUBE")
                        .WithMany("TBL_DERS_PROGRAMIS")
                        .HasForeignKey("SUBE_ID");

                    b.Navigation("DERS");

                    b.Navigation("DONEM");

                    b.Navigation("OGRETMEN");

                    b.Navigation("SCHOOL");

                    b.Navigation("SINIF");

                    b.Navigation("SUBE");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_DERSLER", b =>
                {
                    b.HasOne("EntityLayer.Concrete.TBL_SCHOOL_DURUMLARI", "SCHOOL")
                        .WithMany("TBL_DERSLERS")
                        .HasForeignKey("SCHOOL_ID");

                    b.Navigation("SCHOOL");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_DONEM", b =>
                {
                    b.HasOne("EntityLayer.Concrete.TBL_IDARI_PERSONEL", null)
                        .WithMany("TBL_DONEMS")
                        .HasForeignKey("TBL_IDARI_PERSONELIDARI_PERSONEL_ID");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_IDARI_PERSONEL", b =>
                {
                    b.HasOne("EntityLayer.Concrete.TBL_SCHOOL_DURUMLARI", "SCHOOL")
                        .WithMany("TBL_IDARI_PERSONELS")
                        .HasForeignKey("SCHOOL_ID");

                    b.Navigation("SCHOOL");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_KURUM", b =>
                {
                    b.HasOne("EntityLayer.Concrete.TBL_SCHOOL_DURUMLARI", "SCHOOL")
                        .WithMany("TBL_KURUMS")
                        .HasForeignKey("SCHOOL_ID");

                    b.Navigation("SCHOOL");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_LOG", b =>
                {
                    b.HasOne("EntityLayer.Concrete.TBL_SCHOOL_DURUMLARI", "SCHOOL")
                        .WithMany("TBL_LOGS")
                        .HasForeignKey("SCHOOL_ID");

                    b.Navigation("SCHOOL");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_MESAJ_HAREKETLERI", b =>
                {
                    b.HasOne("EntityLayer.Concrete.TBL_SCHOOL_DURUMLARI", "SCHOOL")
                        .WithMany("TBL_MESAJ_HAREKETLERIS")
                        .HasForeignKey("SCHOOL_ID");

                    b.Navigation("SCHOOL");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_MESAJ_PATH", b =>
                {
                    b.HasOne("EntityLayer.Concrete.TBL_SCHOOL_DURUMLARI", "SCHOOL")
                        .WithMany("TBL_MESAJ_PATHS")
                        .HasForeignKey("SCHOOL_ID");

                    b.Navigation("SCHOOL");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_OGRENCI", b =>
                {
                    b.HasOne("EntityLayer.Concrete.TBL_BOLUM", "BOLUM")
                        .WithMany("TBL_OGRENCIS")
                        .HasForeignKey("BOLUM_ID");

                    b.HasOne("EntityLayer.Concrete.TBL_DONEM", "DONEM")
                        .WithMany("TBL_OGRENCIS")
                        .HasForeignKey("DONEM_ID");

                    b.HasOne("EntityLayer.Concrete.TBL_SCHOOL_DURUMLARI", "SCHOOL")
                        .WithMany("TBL_OGRENCIS")
                        .HasForeignKey("SCHOOL_ID");

                    b.Navigation("BOLUM");

                    b.Navigation("DONEM");

                    b.Navigation("SCHOOL");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_SINIF", b =>
                {
                    b.HasOne("EntityLayer.Concrete.TBL_SCHOOL_DURUMLARI", "SCHOOL")
                        .WithMany("TBL_SINIFS")
                        .HasForeignKey("SCHOOL_ID");

                    b.Navigation("SCHOOL");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_SUBE", b =>
                {
                    b.HasOne("EntityLayer.Concrete.TBL_SCHOOL_DURUMLARI", "SCHOOL")
                        .WithMany("TBL_SUBES")
                        .HasForeignKey("SCHOOL_ID");

                    b.Navigation("SCHOOL");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_TRY_CATCH", b =>
                {
                    b.HasOne("EntityLayer.Concrete.TBL_SCHOOL_DURUMLARI", "SCHOOL")
                        .WithMany("TBL_TRY_CATCHS")
                        .HasForeignKey("SCHOOL_ID");

                    b.Navigation("SCHOOL");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_VELI", b =>
                {
                    b.HasOne("EntityLayer.Concrete.TBL_OGRENCI", "OGRENCI")
                        .WithMany("TBL_VELIS")
                        .HasForeignKey("OGRENCI_ID");

                    b.HasOne("EntityLayer.Concrete.TBL_SCHOOL_DURUMLARI", "SCHOOL")
                        .WithMany("TBL_VELIS")
                        .HasForeignKey("SCHOOL_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OGRENCI");

                    b.Navigation("SCHOOL");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_YOKLAMA_HAREKETLERI", b =>
                {
                    b.HasOne("EntityLayer.Concrete.TBL_DONEM", "DONEM")
                        .WithMany("TBL_YOKLAMA_HAREKETLERIS")
                        .HasForeignKey("DONEM_ID");

                    b.HasOne("EntityLayer.Concrete.TBL_OGRENCI", "OGRENCI")
                        .WithMany("TBL_YOKLAMA_HAREKETLERIS")
                        .HasForeignKey("OGRENCI_ID");

                    b.HasOne("EntityLayer.Concrete.TBL_DERS_PROGRAMI", "PROGRAM")
                        .WithMany("TBL_YOKLAMA_HAREKETLERIS")
                        .HasForeignKey("PROGRAMDERS_PROGRAM_ID");

                    b.HasOne("EntityLayer.Concrete.TBL_SCHOOL_DURUMLARI", "SCHOOL")
                        .WithMany("TBL_YOKLAMA_HAREKETLERIS")
                        .HasForeignKey("SCHOOL_ID");

                    b.Navigation("DONEM");

                    b.Navigation("OGRENCI");

                    b.Navigation("PROGRAM");

                    b.Navigation("SCHOOL");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_BOLUM", b =>
                {
                    b.Navigation("TBL_OGRENCIS");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_DERS", b =>
                {
                    b.Navigation("TBL_DERS_PROGRAMIS");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_DERS_PROGRAMI", b =>
                {
                    b.Navigation("TBL_YOKLAMA_HAREKETLERIS");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_DONEM", b =>
                {
                    b.Navigation("TBL_DERS_PROGRAMIS");

                    b.Navigation("TBL_OGRENCIS");

                    b.Navigation("TBL_YOKLAMA_HAREKETLERIS");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_IDARI_PERSONEL", b =>
                {
                    b.Navigation("TBL_DONEMS");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_OGRENCI", b =>
                {
                    b.Navigation("TBL_VELIS");

                    b.Navigation("TBL_YOKLAMA_HAREKETLERIS");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_SCHOOL_DURUMLARI", b =>
                {
                    b.Navigation("TBL_DERSLERS");

                    b.Navigation("TBL_IDARI_PERSONELS");

                    b.Navigation("TBL_KURUMS");

                    b.Navigation("TBL_LOGS");

                    b.Navigation("TBL_MESAJ_HAREKETLERIS");

                    b.Navigation("TBL_MESAJ_PATHS");

                    b.Navigation("TBL_OGRENCIS");

                    b.Navigation("TBL_SINIFS");

                    b.Navigation("TBL_SUBES");

                    b.Navigation("TBL_TRY_CATCHS");

                    b.Navigation("TBL_VELIS");

                    b.Navigation("TBL_YOKLAMA_HAREKETLERIS");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_SINIF", b =>
                {
                    b.Navigation("TBL_DERS_PROGRAMIS");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TBL_SUBE", b =>
                {
                    b.Navigation("TBL_DERS_PROGRAMIS");
                });
#pragma warning restore 612, 618
        }
    }
}
